export const GET_EMPLOYEES_REQUESTED = 'GET_EMPLOYEES_REQUESTED';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_WORKTIME_REQUESTED = 'GET_WORKTIME_REQUESTED';
export const GET_WORKTIME_SUCCESS = 'GET_WORKTIME_SUCCESS';
export const WORKERS_FAILED = 'WORKERS_FAILED'; 